name: test
run-name: ${{ github.actor }} did a push
on: [push]
jobs:
  run-pytest-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v6
      - name: Touch-file-to-test
        run: touch src/tests/__init__.py
      - name: Check python and install dependencies
        run: |
          python --version
          pip install -r requirements.txt
          pip install pytest
      - name: Run test graph creation
        run: pytest src/tests/test_magneticgraph.py
      - name: Run test laplacian
        run: pytest src/specnet/linalg/tests/test_laplacian.py
      - name: Run test frames
        run: |
          pytest src/specnet/frames/tests/test_frames.py
          pytest src/specnet/frames/tests/test_frames_spectrum.py
