name: test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: touch home/runner/work/specnet/specnet/src/tests/__init__.py
      - run: pip install pytest
      - run: pytest home/runner/work/specnet/specnet/src/tests/test_magnetigraph.py
