name: test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  run-pytest-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v6
      - name: Touch-file-to-test
        run: touch src/tests/__init__.py
      - name: Check python-version
        run: python --version
      - name: Check pytest-version
        run: pytest --version
      - name: Run tests
        run: pytest src/tests/test_magnetigraph.py
